name: 执行定时任务

on:
    # 每16小时执行一次定时任务
    schedule:
        - cron: '59 * * * *'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: 开启node环境
              uses: actions/setup-node@v2.4.0

            - name: Setup Basically Packages
              run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

            - name: 安装依赖
              run: npm install

            - name: Run
              run: node index.js
